### ISSUE TITLE
마일리지 학기별 조회 및 신청 구현

### ISSUE THREAD

**Issue by shinel98** [HisPath/HisPath-Student#2]
**Description**
학생이 마일리지 활동을 조회하고 개인 활동을 마일리지 활동으로 등록할 수 있는 페이지 구현

**Todo**
마일리지 활동 조회
- [x] React로 UI layout
- [x] 카테고리 별로 마일리지 활동 읽어오기
- [ ] 학기별 필터 기능

마일리지 활동 신청
- [x] 해당 학기에 등록된 활동들 읽어오기
- [x] 체크 박스 개별 선택, 일괄 선택으로 마일리지 신청하기

**ETC**
