### ISSUE TITLE
활동 페이지 구현

### ISSUE THREAD

**Issue by songdabin** [HisPath/HisPath-Student#8]
**Description**
- 활동 목록 조회 페이지
- 활동 상세 페이지
- 활동 수정 페이지

**Todo**
- [x] 활동 목록 조회
- [ ] 활동 상세 페이지
- [ ] 활동 수정 페이지
- [ ] 활동, 차트 탭
